src/Entity/Asignaturas.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AsignaturasRepository")
 */
class Asignaturas
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $nombre;

    /**
     * @ORM\Column(type="integer")
     */
    private $creditos;

    /**
     * @ORM\Column(type="integer")
     */
    private $duracion;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_curso;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getCreditos(): ?int
    {
        return $this->creditos;
    }

    public function setCreditos(int $creditos): self
    {
        $this->creditos = $creditos;

        return $this;
    }

    public function getDuracion(): ?int
    {
        return $this->duracion;
    }

    public function setDuracion(int $duracion): self
    {
        $this->duracion = $duracion;

        return $this;
    }

    public function getIdCurso(): ?int
    {
        return $this->id_curso;
    }

    public function setIdCurso(int $id_curso): self
    {
        $this->id_curso = $id_curso;

        return $this;
    }
}

src/Entity/Usuarioasignatura.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsuarioasignaturaRepository")
 */
class Usuarioasignatura
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_usuario;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_asignatura;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUsuario(): ?int
    {
        return $this->id_usuario;
    }

    public function setIdUsuario(int $id_usuario): self
    {
        $this->id_usuario = $id_usuario;

        return $this;
    }

    public function getIdAsignatura(): ?int
    {
        return $this->id_asignatura;
    }

    public function setIdAsignatura(int $id_asignatura): self
    {
        $this->id_asignatura = $id_asignatura;

        return $this;
    }
}

templates/asignaturas.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    <h5>LISTADO DE ASIGNATURAS</h5>
    
    <table class="table">
        <thead>
            {% for curso in cursos %}
               <tr> <th colspan="4"> Asignaturas de  {{curso.curso}}ª {{curso.titulacion}}</th></tr>
        </thead>
        <tbody>
            {% for asignatura in asignaturas %}
            {% if curso.id == asignatura.idCurso %}
            <tr>
            <td> {{asignatura.nombre}}  </td>
            <td>{{asignatura.creditos}} créditos</td>
            <td>{{asignatura.duracion}} horas</td>
                {% if app.session.get('usuario') %}   
                <td> 
                    <a href="{{path('apuntarse', {'id' : asignatura.id }) }}">
                    <button><i class="fa fa-plus"></i> Apuntarse</button>
                    </a> 
                </td>
                {% endif %}
            {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block javascripts %}
   
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"> 
        <!-- Bootstrap CSS -->
        
        <link href="{{ asset ('css/bootstrap.css') }}" rel="stylesheet" >
        <link href="{{ asset ('estilo.css') }}" rel="stylesheet" >
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <title>{% block title %}PRUEBA TÉCNICA{% endblock %}</title>
        {% block stylesheets %}
        
        {% endblock %}
    </head>
    <body> 

        <h2 class="title">PRUEBA TÉCNICA SYMFONY 5</h2>

        <ul class="menu">
            <li class="menu-list"><a href="{{ ('/asignaturas') }}">ASIGNATURAS</a></li>
            <li class="menu-list"><a href="{{ ('/cursos') }}">CURSOS</a></li>
         {% if app.session.get('usuario') %}   
         <li class="menu-list"><a href="{{ ('/misdatos') }}">MIS DATOS</a></li>
        <span>
        Bienvenid@ {{app.session.get('usuario')}}</span>
         <button><a  href="{{'/logout'}}">LOGOUT</a></button> 
        {% else %}
            <li class="menu-list"><a href="{{ ('/') }}">LOGIN</a></li>
            <li class="menu-list"><a href="{{ ('/registro') }}">REGISTRARSE</a></li>
        {% endif %}
        
        </ul>
        {% block body %}{% endblock %}
        {% block javascripts %}
       
        {% endblock %}
    
    </body>
</html>

templates/cursos.html.twig
{% extends 'base.html.twig' %}

    {% block stylesheets %}
        {{parent()}}
    {% endblock %}

    {% block body %}
        
        <h5>LISTADO DE CURSOS</h5>
        
        <table class="table">
            <thead>
                <th>Curso</th>
                <th>Duración (meses)</th>
                <th>Año académico</th>
                <th></th>
            </thead>
            <tbody>
                {% for curso in cursos %}
                <tr>
                <td> {{curso.curso}}ª {{curso.titulacion}}</td>
                <td> {{curso.duracion}}</td>
                <td> {{curso.anio}}</td>
                <td>
                    <button> <a href="{{path('detalles', {'id' : curso.id })}}"> Ver más <i class="fa fa-info-circle"></i></a></button>
                </td>
            </tr>
                {% endfor %}
            </tbody>

        </table>
            <button>
                <a href="{{('/nuevocurso')}}"> Nuevo curso</a> </button>
    {% endblock %}

    {% block javascripts %}
       
    {% endblock %}
    

templates/detalles.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    <h4 class="mb-2"> {{curso.curso}}ª {{curso.titulacion}} </h4>
    
    <table class="table">
        <thead>
            <tr>
                <th colspan="4">Duración total del curso: {{curso.duracion}} meses</th>
            </tr> 
            <tr>
            <th>Asignaturas</th>
            <th>Créditos</th>
            <th>Duración (horas)</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
            {% for asignatura in asignaturas %}
                {% if curso.id == asignatura.idCurso %}
                <tr>
                    <td>{{asignatura.nombre}}</td>
                    <td>{{asignatura.creditos}}</td>
                    <td>{{asignatura.duracion}} horas</td>
                    <td> 
                        <a href="{{path('detalleasignatura', {'id' : asignatura.id }) }}">
                        <button><i class="fa fa-pencil"></i> Editar</button>
                        </a> <a href="{{path('borrarasig', {'id' : asignatura.id }) }}">
                        <button><i class="fa fa-trash"></i> Eliminar</button>
                        </a> 
                </tr>
                {% endif %}
            {% endfor %}
        
        </tbody>
    </table>
        <button> <a href="{{path('nuevaasignatura', {'id' : curso.id }) }}"> Añadir asignatura </a></button>
        
        <button> <a href="{{('/cursos')}}"> Atrás </a></button>
{% endblock %}

{% block javascripts %}
   
{% endblock %}

templates/detallesasignatura.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    <h5>EDITAR ASIGNATURA</h5>
    
    <form class="form" action="{{path ('editarasignatura', { 'id' : asignatura.id }) }}">
        <label class="field" for="nombre" >Nombre: * </label>
        <input class="field" type="nombre" value="{{asignatura.nombre}}" name="nombre" required >
        <label class="field" for="creditos">Créditos: * </label>
        <input class="field" type="number" value="{{asignatura.creditos}}" name="creditos" required>
        <label class="field" for="duracion">Duración (en meses): *</label>
        <input class="field" type="text" value="{{asignatura.duracion}}" name="duracion" required>
      
        <input class="mt-3" type="submit"  value="Editar">
        <a href="{{path('detalles', {'id' : asignatura.idCurso }) }}"> 
            <input class="mt-3" type="button"  value="Atrás">
        </a>
    </form>
{% endblock %}

{% block javascripts %}
   
{% endblock %}

templates/editardatos.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    <h5>EDITAR MIS DATOS</h5>
    
    <form class="form" action="{{ ('/editardatos') }}">
        <label class="field" for="usuario" >Usuario: * </label>
        <input class="field" type="usuario" value="{{usuario.usuario}}" name="usuario" required >
        <label class="field" for="nombre">Nombre: * </label>
        <input class="field" type="text" value="{{usuario.nombre}}" name="nombre" required>
        <label class="field" for="apellidos">Apellidos: *</label>
        <input class="field" type="text" value="{{usuario.apellidos}}" name="apellidos" required>
        <label class="field" for="email"> Email: *</label>
        <input class="field" type="text" value="{{usuario.email}}" name="email" required>
        <label class="field" for="pass"> Nueva contraseña: *</label>
        <input class="field" type="password" name="pass" required>

        <input class="mt-3 mb-3" type="submit" value="Editar">
    </form>
    <button><a href="{{ ('/misdatos') }}"> Atrás</a></button>
{% endblock %}

{% block javascripts %}
   
{% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    <h5>LOGIN</h5>
    
    <form class="form" action="{{ ('/logearse') }}">
        <label class="field" for="usuario" >Usuario: * </label>
        <input class="field" type="usuario" name="usuario" required >
        <label class="field" for="pass"> Contraseña: *</label>
        <input class="field" type="password" name="pass" required>

        <input class="mt-3" type="submit" value="Añadir">
    </form>
    <div class="tex-center">
        <p>¿No estás registrado?</p>
        <p> <a href="{{('/registro')}}">Registrate ahora</a></p>
    </div>
{% endblock %}

{% block javascripts %}
   
{% endblock %}

templates/misdatos.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    <h5> MIS DATOS </h5>
    
    <table class="table">
        <thead></thead>
        <tbody>
            <tr>
                <td colspan="2"> Usuario: {{usuario.usuario}}</td>
            </tr>
            <tr>
                <td> Nombre: {{usuario.nombre}} {{usuario.apellidos}}</td>
                <td> Email: {{usuario.email}}</td>
            </tr>
        </tbody>
    </table>

    <table class="table">
          <thead>
            <tr>
                <th colspan="2"> Mis asignaturas: </td>
            </tr>
            <tr>
                <th>Asignatura</th>
                <th>Curso</th>
            </tr>
        </thead>
        <tbody>
            {% for miasignatura in misasignaturas %}
                {% if miasignatura.idUsuario == usuario.id %}
                    {% for asignatura in asignaturas %}
                        {% if asignatura.id == miasignatura.idAsignatura %}
                        <tr>
                        <td>{{ asignatura.nombre}}</td>
                        {% for curso in cursos %}
                            {% if curso.id == asignatura.idCurso %}
                            <td> {{curso.curso}}ª {{curso.titulacion}}</td>
                            {% endif %}
                        {% endfor %}
                        </tr>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    

    <button><i class="fa fa-pencil"></i><a href="{{('/formulariodatos')}}"> Editar datos</a></button>
    <button><i class="fa fa-plus"></i><a href="{{ ('/asignaturas') }}"> Apuntarse a asignaturas</a></button>

{% endblock %}

{% block javascripts %}
   
{% endblock %}

templates/nuevaasignatura.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    <h5>AÑADIR ASIGNATURA A: {{curso.curso}}ª {{curso.titulacion}}</h5>
    
    <form class="form" action="{{path('crearasig', {'id' : curso.id })}}">
        <label class="field" for="curso">Curso: </label>
        <input class="field" type="text" name="idcurso" value="{{curso.curso}}ª {{curso.titulacion}}" disabled>
        <label class="field" for="nombre">Asignatura: </label>
        <input class="field" type="text" name="nombre">
        <label class="field" for="creditos">Créditos</label>
        <input class="field" type="text" name="creditos">
        <label class="field" for="duracion">Duración (horas)</label>
        <input class="field" type="text" name="duracion">

        <input class="mt-3 mb-3" type="submit" value="Añadir">
    </form>

    <button><a href="{{path('detalles', {'id' : curso.id })}}"> Atrás</a></button>
{% endblock %}

{% block javascripts %}
   
{% endblock %}

templates/nuevocurso.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    <h5>AÑADIR CURSO</h5>
    
    <form class="form" action="{{('/crearcurso')}}">
        <label class="field" for="titulacion" >Curso: </label>
        <input class="field mb-1" placeholder="1, 2..." type="number" required name="curso">
        <input class="field" type="text" required name="titulacion">
        <label class="field" for="duracion">Duración del curso: </label>
        <input class="field" type="text" required name="duracion">
        <label class="field" for="anio">Año académico: </label>
        <input class="field" type="text"  required placeholder="Ej: 2020 - 2021" name="anio">

        <input class="mt-3 mb-3" type="submit" value="Añadir">
    </form>
    
    <button><a href="{{ ('/cursos') }}"> Atrás</a></button>
{% endblock %}

{% block javascripts %}
   
{% endblock %}

templates/registro.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    <h5>FORMULARIO DE REGISTRO</h5>
    
    <form class="form" action="{{ ('/nuevousuario') }}">
        <label class="field" for="usuario" >Usuario: * </label>
        <input class="field" type="usuario" name="usuario" required >
        <label class="field" for="nombre">Nombre: * </label>
        <input class="field" type="text" name="nombre" required>
        <label class="field" for="apellidos">Apellidos: *</label>
        <input class="field" type="text" name="apellidos" required>
        <label class="field" for="email"> Email: *</label>
        <input class="field" type="text" name="email" required>
        <label class="field" for="pass"> Contraseña: *</label>
        <input class="field" type="password" name="pass" required>

        <input class="mt-3" type="submit" value="Registrarse">
    </form>
{% endblock %}

{% block javascripts %}
   
{% endblock %}